# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_at',
            new_name='appointment_time',
        ),
    ]
