# Generated by Django 6.0.6 on 2026-07-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rename_scheduled_at_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_time')},
        ),
    ]
